name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-12
    name: 3.1
    steps:
    - uses: actions/checkout@v3
    - name: OpenBSD Test
      id: test
      uses: vmactions/openbsd-vm@v0
      with:
        prepare: |
          pkg_add ruby%3.1
          gem31 install -N rake-compiler minitest-global_expectations
        run: |
          ftp -o - https://cdn.openbsd.org/pub/OpenBSD/7.2/amd64/comp72.tgz | tar zxpf - -C /
          rake31
