name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: 3.4
    steps:
    - uses: actions/checkout@v6
    - name: OpenBSD Test
      id: test
      uses: vmactions/openbsd-vm@v1
      with:
        release: 7.8
        prepare: |
          pkg_add ruby%3.4
          gem34 install -N rake-compiler minitest-global_expectations
        run: |
          ftp -o - https://cdn.openbsd.org/pub/OpenBSD/7.8/amd64/comp78.tgz | tar zxpf - -C /
          rake34
